# Generated by Django 6.0.1 on 2026-02-10 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_profile_rejection_reason_profile_verified_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="verification_submitted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="verification_submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
