# Generated by Django 6.0.1 on 2026-02-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_profile_verification_submitted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="full_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
