# Generated by Django 6.0.1 on 2026-02-11 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_profile_full_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "name_so",
                    models.CharField(
                        blank=True, help_text="Somali name", max_length=50
                    ),
                ),
                (
                    "flag_emoji",
                    models.CharField(blank=True, help_text="Flag emoji", max_length=10),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Degmo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "name_so",
                    models.CharField(
                        blank=True, help_text="Somali name", max_length=100
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="degmo",
                        to="users.state",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("state", "name")},
            },
        ),
        migrations.CreateModel(
            name="Magaalo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "name_so",
                    models.CharField(
                        blank=True, help_text="Somali name", max_length=50
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "degmo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="magaalo",
                        to="users.degmo",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("degmo", "name")},
            },
        ),
    ]
