# Generated by Django 6.0.1 on 2026-02-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_state_degmo_magaalo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="state",
            name="flag_emoji",
        ),
        migrations.AddField(
            model_name="state",
            name="flag_image",
            field=models.ImageField(
                blank=True,
                help_text="State flag image",
                null=True,
                upload_to="state_flags/",
            ),
        ),
    ]
