# Generated by Django 6.0.1 on 2026-01-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="announcements/"
                    ),
                ),
                ("content", models.TextField(blank=True)),
                (
                    "target_audience",
                    models.CharField(
                        choices=[
                            ("all", "Global"),
                            ("agents", "Agents Only"),
                            ("customers", "Customers Only"),
                        ],
                        default="all",
                        max_length=20,
                    ),
                ),
                ("action_link", models.URLField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("priority", models.IntegerField(default=1)),
            ],
        ),
    ]
