# Generated by Django 6.0.1 on 2026-01-10 16:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="announcement",
            name="start_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
