# Generated by Django 6.0.1 on 2026-01-10 16:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "listing_type",
                    models.CharField(
                        choices=[
                            ("sale", "For Sale"),
                            ("rent", "For Rent"),
                            ("short_stay", "Short Stay"),
                        ],
                        max_length=20,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("city", models.CharField(max_length=50)),
                ("district", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=255)),
                ("bedrooms", models.IntegerField()),
                ("bathrooms", models.IntegerField()),
                ("area_sqm", models.IntegerField()),
                ("description", models.TextField()),
                ("main_photo", models.ImageField(upload_to="listings/%Y/%m/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending Review"),
                            ("active", "Active"),
                            ("rejected", "Rejected"),
                            ("sold", "Sold/Rented"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="PropertyLead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("owner_name", models.CharField(max_length=100)),
                ("owner_phone", models.CharField(max_length=20)),
                ("property_type", models.CharField(max_length=50)),
                ("location", models.CharField(max_length=100)),
                ("status", models.CharField(default="new", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
