# Generated by Django 6.0.1 on 2026-02-11 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "properties",
            "0003_alter_listing_options_remove_listing_listing_type_and_more",
        ),
        ("users", "0005_state_degmo_magaalo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="city",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="district",
        ),
        migrations.AddField(
            model_name="listing",
            name="degmo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="listings",
                to="users.degmo",
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="degmo_text",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="listing",
            name="magaalo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="listings",
                to="users.magaalo",
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="magaalo_text",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="listing",
            name="state_text",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="listing",
            name="main_photo",
            field=models.ImageField(
                blank=True, default="", upload_to="listings/%Y/%m/"
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="state",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="listings",
                to="users.state",
            ),
        ),
    ]
