# Generated by Django 6.0.1 on 2026-02-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0004_remove_listing_city_remove_listing_district_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="floor",
            field=models.IntegerField(
                blank=True, help_text="Qaybta / Floor", null=True
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="has_corridor_access",
            field=models.BooleanField(
                default=False, help_text="Coridor / Corridor Access"
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="has_loading_dock",
            field=models.BooleanField(default=False, help_text="Dayax / Loading Dock"),
        ),
        migrations.AddField(
            model_name="listing",
            name="height_meters",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Dhererka (meters)",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="is_furnished",
            field=models.BooleanField(default=False, help_text="Furnished / Qalalan"),
        ),
        migrations.AddField(
            model_name="listing",
            name="kitchens",
            field=models.IntegerField(
                blank=True, help_text="Musqul Kutaaxan", null=True
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="land_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("residential", "Gurigeliyada / Residential"),
                    ("commercial", "Ganacsi / Commercial"),
                    ("agricultural", "Beerasho / Agricultural"),
                    ("industrial", "Tignolaaysan / Industrial"),
                    ("mixed", "Mixed Use"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="living_rooms",
            field=models.IntegerField(
                blank=True, help_text="Qolka Nololaha", null=True
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="parking_spots",
            field=models.IntegerField(
                blank=True, help_text="Baasto / Parking", null=True
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="year_built",
            field=models.IntegerField(
                blank=True, help_text="Sanadka la dhisay", null=True
            ),
        ),
    ]
