# Generated by Django 6.0.1 on 2026-02-11 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0005_listing_floor_listing_has_corridor_access_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "name_so",
                    models.CharField(
                        blank=True, help_text="Somali name", max_length=50
                    ),
                ),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Material icon name", max_length=50
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Property Category",
                "verbose_name_plural": "Property Categories",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.RemoveField(
            model_name="listing",
            name="property_category",
        ),
        migrations.AddField(
            model_name="listing",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="listings",
                to="properties.propertycategory",
            ),
        ),
        migrations.CreateModel(
            name="PropertySubtype",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "name_so",
                    models.CharField(
                        blank=True, help_text="Somali name", max_length=100
                    ),
                ),
                ("slug", models.SlugField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtypes",
                        to="properties.propertycategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Property Subtype",
                "verbose_name_plural": "Property Subtypes",
                "ordering": ["sort_order", "name"],
                "unique_together": {("category", "name")},
            },
        ),
        migrations.AddField(
            model_name="listing",
            name="subtype",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="listings",
                to="properties.propertysubtype",
            ),
        ),
    ]
