# Generated by Django 6.0.1 on 2026-02-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "properties",
            "0006_propertycategory_remove_listing_property_category_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="price_period",
            field=models.CharField(
                blank=True,
                choices=[("month", "Bishii / Monthly"), ("year", "Sanadkii / Yearly")],
                default="",
                max_length=10,
            ),
        ),
    ]
