# Generated by Django 6.0.1 on 2026-04-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0008_favorite"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="features",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Enter features as bullet points (one per line starting with -)",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="floor",
            field=models.IntegerField(
                blank=True, help_text="Dabaqa / Floor", null=True
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="kitchens",
            field=models.IntegerField(blank=True, help_text="Musqul", null=True),
        ),
        migrations.AlterField(
            model_name="listing",
            name="living_rooms",
            field=models.IntegerField(blank=True, help_text="Qolka Fadhiga", null=True),
        ),
        migrations.AlterField(
            model_name="listing",
            name="parking_spots",
            field=models.IntegerField(
                blank=True, help_text="Baarkin / Parking", null=True
            ),
        ),
    ]
