# Generated by Django 6.0.1 on 2026-04-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0009_listing_features_alter_listing_floor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="area_length",
            field=models.IntegerField(
                blank=True, help_text="Length in meters", null=True
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="area_width",
            field=models.IntegerField(
                blank=True, help_text="Width in meters", null=True
            ),
        ),
    ]
